# Generated by Django 4.2.27 on 2026-01-15 01:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import teacher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(default='000000', max_length=6)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teacher.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=2048, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teacher.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', max_length=512)),
                ('profile_pic', models.ImageField(blank=True, default='default/profile.jpg', null=True, upload_to=teacher.models.upload_to)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField(default=1)),
                ('question', models.CharField(max_length=600)),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=200)),
                ('exam', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teacher.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=teacher.models.upload_imagebox)),
                ('date', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teacher.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('doc_file', models.FileField(upload_to=teacher.models.upload_document, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'docx', 'txt'])])),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', models.CharField(blank=True, default='ไม่มีรายละเอียดประกอบ', max_length=2048, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.course')),
            ],
        ),
    ]
