# Generated by Django 4.2.27 on 2026-01-15 01:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('context', models.TextField(max_length=1024)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('announce', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to=home.models.news_upload)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default/classroom.jpg', null=True, upload_to=home.models.upload_to)),
                ('join_code', models.CharField(default='000000', max_length=6)),
                ('commit', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('description', models.TextField(blank=True, default='No description', max_length=300, null=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('math', 'การคำนวณ'), ('data', 'การวิเคราะห์ข้อมูล'), ('it', 'เทคโนโลยีสารสนเทศ'), ('programming', 'การเขียนโปรแกรม'), ('development', 'การพัฒนาซอฟต์แวร์'), ('ai', 'ปัญญาประดิษฐ์'), ('design', 'การออกแบบ'), ('economics', 'การเงิน/การลงทุน'), ('marketing', 'การตลาด'), ('philosophy', 'ปรัชญา'), ('language', 'ภาษา'), ('health', 'สุขภาพ'), ('selfdev', 'การพัฒนาตนเอง'), ('other', 'อื่นๆ')], default='other', max_length=20)),
                ('owner', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
